gitea:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  podAnnotations:
    backup.velero.io/backup-volumes: data
  config:
    server:
      SSH_PORT: 22
      SSH_LISTEN_PORT: 11022
      DOMAIN: gitea.${domain}
      ROOT_URL: https://gitea.${domain}
    database:
      DB_TYPE: postgres
      HOST: db.postgres
      NAME: gitea
      USER: gitea
      PASSWD: ${db_password}
    indexer:
      REPO_INDEXER_ENABLED: true
    mailer:
      ENABLED: true
      FROM: gitea@${domain}
      HOST: ${smtp_host}
      USER: ${smtp_user}
      PASSWD: ${smtp_password}
    service:
      DISABLE_REGISTRATION: true
    repository:
      DEFAULT_BRANCH: main
    metrics:
      ENABLED_ISSUE_BY_REPOSITORY: true
      ENABLED_ISSUE_BY_LABEL: true
    webhook:
      ALLOWED_HOST_LIST: "*"

postgresql:
  enabled: false

memcached:
  enabled: false

persistence:
  storageClass: nfs-client

tolerations:
  - key: node-role.kubernetes.io/runner
    operator: Exists
