initChownData:
  enabled: false

persistence:
  enabled: true
  storageClassName: nfs-client

serviceMonitor:
  enabled: true

sidecar:
  dashboards:
    enabled: true

tolerations:
  - key: node-role.kubernetes.io/monitor
    operator: Exists

podAnnotations:
  backup.velero.io/backup-volumes: storage
