loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  rulerConfig:
    storage:
      type: local

singleBinary:
  replicas: 1
  tolerations:
    - key: node-role.kubernetes.io/monitor
      operator: Exists
  persistence:
    storageClass: local-path

monitoring:
  selfMonitoring:
    enabled: false

    lokiCanary:
      enabled: false

    grafanaAgent:
      installOperator: false

test:
  enabled: false
