prometheusOperator:
  image:
    tag: v0.60.1
  prometheusConfigReloader:
    image:
      tag: v0.60.1

prometheus:
  prometheusSpec:
    image:
      tag: v2.39.1
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 8Gi
    tolerations:
      - key: node-role.kubernetes.io/monitor
        operator: Exists

alertmanager:
  enabled: false

grafana:
  enabled: false
  forceDeployDashboards: true
