prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: openebs-hostpath
          resources:
            requests:
              storage: 8Gi
    tolerations:
      - key: node-role.kubernetes.io/monitor
        operator: Exists

alertmanager:
  enabled: false

grafana:
  enabled: false
  forceDeployDashboards: true
