deployment:
  kind: DaemonSet

ingressRoute:
  dashboard:
    enabled: false

ports:
  ssh:
    port: 2222
    expose: true
    exposedPort: 22
    protocol: TCP
  web:
    redirectTo: websecure
  websecure:
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
    tls:
      enabled: true

logs:
  access:
    enabled: true

metrics:
  prometheus:
    serviceMonitor:
      namespaceSelector: {}

hub:
  enabled: true

tracing:
  jaeger:
    samplingServerURL: http://jaeger-agent.tracing:5778/sampling
    localAgentHostPort: jaeger-agent.tracing:6831
