deployment:
  kind: DaemonSet

ingressRoute:
  dashboard:
    enabled: false

ports:
  ssh:
    port: 2222
    expose: true
    exposedPort: 22
    protocol: TCP
  web:
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true

logs:
  access:
    enabled: true

metrics:
  prometheus:
    serviceMonitor:
      namespaceSelector: {}

hub:
  enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
