configuration:
  provider: gcp

initContainers:
  - name: velero-plugin-for-gcp
    image: velero/velero-plugin-for-gcp:v1.5.0
    volumeMounts:
      - mountPath: /target
        name: plugins

metrics:
  serviceMonitor:
    enabled: true

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
