prometheus:
  servicemonitor:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 64Mi

webhook:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 32Mi

cainjector:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 64Mi
