container_runtime: containerd

lapi:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  persistentVolume:
    data:
      existingClaim: crowdsec-db
    config:
      existingClaim: crowdsec-config

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      program: traefik

  env:
    - name: PARSERS
      value: crowdsecurity/cri-logs
    - name: COLLECTIONS
      value: crowdsecurity/traefik crowdsecurity/http-cve

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
