deployment:
  replicas: 2

ingressRoute:
  dashboard:
    entryPoints:
      - internal
    matchRule: Host(`traefik.int.${domain}`)
    middlewares:
      - name: middleware-auth

ports:
  ssh:
    port: 2222
    expose: true
    exposedPort: 22
    protocol: TCP
  web:
    redirectTo:
      port: websecure
  websecure:
    middlewares:
      - traefik-middleware-compress@kubernetescrd
  internal:
    port: 9443
    expose: true
    exposedPort: 8443
    protocol: TCP
    tls:
      enabled: true
    forwardedHeaders:
      trustedIPs:
        - "10.0.0.0/8"
    proxyProtocol:
      trustedIPs:
        - "10.0.0.0/8"
    middlewares:
      - traefik-middleware-internal-ip@kubernetescrd

logs:
  access:
    enabled: true
    format: json
    fields:
      headers:
        names:
          X-B3-TraceId: keep

tracing:
  zipkin:
    httpEndpoint: http://tempo.tracing:9411/api/v2/spans
    sameSpan: true
    id128Bit: true
    sampleRate: 1.0

metrics:
  prometheus:
    serviceMonitor:
      namespaceSelector: {}

providers:
  kubernetesCRD:
    allowCrossNamespace: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 256Mi
