deployment:
  kind: DaemonSet

ingressRoute:
  dashboard:
    entryPoints:
      - websecure
    matchRule: Host(`traefik.${domain}`)
    middlewares:
      - name: middleware-auth

ports:
  ssh:
    port: 2222
    expose: true
    exposedPort: 22
    protocol: TCP
  web:
    redirectTo: websecure
  websecure:
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
    tls:
      enabled: true

logs:
  access:
    enabled: true
    format: json
    fields:
      headers:
        names:
          X-B3-TraceId: keep

tracing:
  zipkin:
    httpEndpoint: http://tempo.tracing:9411/api/v2/spans
    sameSpan: true
    id128Bit: true
    sampleRate: 1.0

providers:
  kubernetesCRD:
    allowCrossNamespace: true
