serviceMonitor:
  enabled: true

deploymentStrategy:
  type: Recreate

sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 384Mi
