serviceMonitor:
  enabled: true

sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true

tolerations:
  - key: node-role.kubernetes.io/storage
    operator: Exists
nodeSelector:
  node-role.kubernetes.io/primary: "true"
