serviceMonitor:
  enabled: true

deploymentStrategy:
  type: Recreate

sidecar:
  alerts:
    enabled: true
  datasources:
    enabled: true
  dashboards:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 384Mi

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    top-line:
      gnetId: 15474
      revision: 4
    health:
      gnetId: 15486
      revision: 3
    kubernetes:
      gnetId: 15479
      revision: 2
    namespace:
      gnetId: 15478
      revision: 3
    deployment:
      gnetId: 15475
      revision: 6
    pod:
      gnetId: 15477
      revision: 3
    service:
      gnetId: 15480
      revision: 3
    route:
      gnetId: 15481
      revision: 3
    authority:
      gnetId: 15482
      revision: 3
    cronjob:
      gnetId: 15483
      revision: 3
    job:
      gnetId: 15487
      revision: 3
    daemonset:
      gnetId: 15484
      revision: 3
    replicaset:
      gnetId: 15491
      revision: 3
    statefulset:
      gnetId: 15493
      revision: 3
    replicationcontroller:
      gnetId: 15492
      revision: 4
    prometheus:
      gnetId: 15489
      revision: 2
    prometheus-benchmark:
      gnetId: 15490
      revision: 2
    multicluster:
      gnetId: 15488
      revision: 3
    certmanager:
      gnetId: 20842
      revision: 2
    traefik:
      gnetId: 17347
      revision: 8
    crowdsec:
      url: https://raw.githubusercontent.com/crowdsecurity/grafana-dashboards/master/dashboards_v5/Crowdsec%20Overview.json
    longhorn:
      gnetId: 16888
      revision: 9
    cloudflared:
      gnetId: 17457
      revision: 6
      datasource:
        - name: DS_PROMETHEUS
          value: prometheus
    redis:
      gnetId: 763
      revision: 6
      datasource:
        - name: DS_PROM
          value: prometheus
