serviceMonitor:
  enabled: true

sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true

tolerations:
  - key: "node-role.kubernetes.io/monitor"
    operator: "Exists"
nodeSelector:
  node-role.kubernetes.io/monitor: "true"
