serviceMonitor:
  enabled: true

sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 384Mi
  limits:
    cpu: 1000m
    memory: 384Mi

tolerations:
  - key: node-role.kubernetes.io/monitor
    operator: Exists

nodeSelector:
  node-role.kubernetes.io/monitor: "true"
