initChownData:
  enabled: false

persistence:
  enabled: true
  existingClaim: ${pvc_name}

deploymentStrategy:
  type: Recreate

serviceMonitor:
  enabled: true

sidecar:
  dashboards:
    enabled: true

tolerations:
  - key: "node-role.kubernetes.io/storage"
    operator: "Exists"
nodeSelector:
  node-role.kubernetes.io/storage: "true"
