loki:
  auth_enabled: false
  compactor:
    retention_enabled: true
    delete_request_store: s3
  limits_config:
    retention_period: ${retention_period}
  storage:
    bucketNames:
      chunks: ${bucket}
      ruler: ${bucket}
      admin: ${bucket}
    s3:
      endpoint: ${endpoint}
      region: ${region}
      accessKeyId: ${access_key}
      secretAccessKey: ${secret_key}
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

gateway:
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 1000m
      memory: 32Mi

read:
  replicas: 1
  tolerations:
    - key: node-role.kubernetes.io/monitor
      operator: Exists
  nodeSelector:
    node-role.kubernetes.io/monitor: "true"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

backend:
  replicas: 1
  tolerations:
    - key: node-role.kubernetes.io/monitor
      operator: Exists
  nodeSelector:
    node-role.kubernetes.io/monitor: "true"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 256Mi

write:
  replicas: 2
  tolerations:
    - key: node-role.kubernetes.io/storage
      operator: Exists
  nodeSelector:
    node-role.kubernetes.io/storage: "true"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 128Mi

monitoring:
  dashboards:
    namespace: monitoring
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

test:
  enabled: false

chunksCache:
  enabled: false

resultsCache:
  enabled: false

lokiCanary:
  enabled: false
