loki:
  auth_enabled: false
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: 24h
  storage:
    bucketNames:
      chunks: ${bucket}
      ruler: ${bucket}
      admin: ${bucket}
    s3:
      endpoint: ${endpoint}
      region: ${region}
      accessKeyId: ${access_key}
      secretAccessKey: ${secret_key}

read:
  replicas: 1

backend:
  replicas: 1
  tolerations:
    - key: node-role.kubernetes.io/storage
      operator: Exists
  nodeSelector:
    node-role.kubernetes.io/storage: "true"

write:
  replicas: 2
  tolerations:
    - key: node-role.kubernetes.io/storage
      operator: Exists
  nodeSelector:
    node-role.kubernetes.io/storage: "true"

monitoring:
  dashboards:
    namespace: monitoring
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

test:
  enabled: false
