tolerations:
  - effect: NoSchedule
    operator: Exists

service:
  enabled: true

serviceMonitor:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 96Mi
