kubeControllerManager:
  endpoints:
    - 192.168.42.10
    - 192.168.42.11
    - 192.168.42.12
kubeScheduler:
  endpoints:
    - 192.168.42.10
    - 192.168.42.11
    - 192.168.42.12
kubeProxy:
  endpoints:
    - 192.168.42.10
    - 192.168.42.11
    - 192.168.42.12
kubeEtcd:
  endpoints:
    - 192.168.42.10
    - 192.168.42.11
    - 192.168.42.12

prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 5GB
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    enableRemoteWriteReceiver: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 8Gi
    tolerations:
      - key: node-role.kubernetes.io/monitor
        operator: Exists
    nodeSelector:
      node-role.kubernetes.io/monitor: "true"

alertmanager:
  enabled: false

grafana:
  enabled: false
  forceDeployDatasources: true
  forceDeployDashboards: true
