tempo:
  retention: ${retention_period}
  storage:
    trace:
      backend: s3
      s3:
        bucket: ${bucket}
        endpoint: ${endpoint}
        region: ${region}
        access_key: ${access_key}
        secret_key: ${secret_key}
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-operated.monitoring:9090/api/v1/write
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 1Gi

serviceMonitor:
  enabled: true

tolerations:
  - key: node-role.kubernetes.io/runner
    operator: Exists

nodeSelector:
  node-role.kubernetes.io/runner: "true"
