tempo:
  retention: ${retention_period}
  storage:
    trace:
      backend: s3
      s3:
        bucket: ${bucket}
        endpoint: ${endpoint}
        region: ${region}
        access_key: ${access_key}
        secret_key: ${secret_key}
  receivers:
    zipkin:
      endpoint: 0.0.0.0:9411
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-operated.monitoring:9090/api/v1/write
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 512Mi

serviceMonitor:
  enabled: true
